name: TICKET-MATE-BE-PR-BUILD

on:
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 최적 설정
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Github Secret 내부 설정 파일 동적 생성
        shell: bash
        run: |
          echo "${{ secrets.TICKETMATE_FIREBASE_KEY_JSON }}" | sed 's/\\n/\n/g' > ticketmate-api/src/main/resources/ticketmate-firebase-key.json
          cat << 'EOF' > ticketmate-api/src/main/resources/static/firebase-messaging-sw.js
          ${{ secrets.FIREBASE_MESSAGING_SW_JS }}
          EOF
          echo "${{ secrets.TICKETMATE_EMBEDDING_JSON }}" | sed 's/\\n/\n/g' > ticketmate-api/src/main/resources/ticketmate-embedding.json
          echo "${{ secrets.CONFIG_IMPORTS_YML }}" > ticketmate-api/src/main/resources/config-imports.yml
          echo "${{ secrets.OAUTH2_YML }}" > ticketmate-api/src/main/resources/oauth2.yml
          echo "${{ secrets.AWS_S3_YML }}" > ticketmate-api/src/main/resources/aws-s3.yml
          echo "${{ secrets.MESSAGING_YML }}" > ticketmate-api/src/main/resources/messaging.yml
          echo "${{ secrets.SPRINGDOC_YML }}" > ticketmate-api/src/main/resources/springdoc.yml
          echo "${{ secrets.ADMIN_YML }}" > ticketmate-api/src/main/resources/admin.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" > ticketmate-api/src/main/resources/application-prod.yml

      # prod 프로파일을 활성화하여 빌드 ( 테스트 코드 테스트 X )
      - name: Build with Gradle
        run: ./gradlew build -x test -Dspring.profiles.active=prod