name: TICKET-MATE-BE-PR-BUILD

on:
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # firebase sdk 파일을 빌드 전에 생성
      - name: Create ticketmate-firebase-key.json from secret
        run: |
          echo "${{ secrets.TICKETMATE_FIREBASE_KEY_JSON }}" > ./src/main/resources/ticketmate-firebase-key.json

      # firebase 서비스워커 파일을 빌드 전에 생성
      - name: Create firebase-messaging-sw.js from secret
        run: |
          echo "${{ secrets.FIREBASE_MESSAGING_SW_JS }}" > ./src/main/resources/static/firebase-messaging-sw.js     

      # embedding.json 파일을 빌드 전에 생성
      - name: Create embedding.json from secret
        run: |
          echo "${{ secrets.TICKETMATE_EMBEDDING_JSON }}" > ./src/main/resoruces/ticketmate-embedding.json

      # oauth2.yml 파일을 빌드 전에 생성
      - name: Create oauth2.yml from secret
        run: |
          echo "${{ secrets.OAUTH2_YML }}" > ./src/main/resources/oauth2.yml

      # application-prod.yml 파일을 빌드 전에 생성
      - name: Create application-prod.yml from secret
        run: |
          echo "${{ secrets.APPLICATION_PROD_YML }}" > ./src/main/resources/application-prod.yml

      # prod 프로파일을 활성화하여 빌드 ( 테스트 코드 테스트 X )
      - name: Build with Gradle
        run: ./gradlew clean build -x test -Dspring.profiles.active=prod