spring:
  main:
    web-application-type: none

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate  # [CHANGED] DB 변경 없이 매핑-스키마 호환성 검증
    properties:
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: none  # DB에는 적용하지 않음
            scripts:
              action: create
              create-target: ${user.dir}/ticketmate-api/build/generated/hibernate-ddl.sql
      hibernate:
        format_sql: true
        show_sql: false
        # 스키마 생성을 강제로 활성화
        hbm2ddl:
          schema_generation:
            script:
              append: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    baseline-version: 1
    baseline-description: "Initial baseline"

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.reactive.ReactiveOAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration
      - org.springframework.boot.autoconfigure.rabbit.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

  # 로깅 레벨 조정으로 디버깅 정보 확인
logging:
  level:
    org.hibernate: DEBUG
    org.hibernate.tool.schema: DEBUG
    org.flywaydb: DEBUG
    org.springframework.orm.jpa: DEBUG
