spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: validate  # [CHANGED] DB 변경 없이 매핑-스키마 호환성 검증
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # (선택) 네이밍 전략을 명시하면 Flyway SQL과 이름 차이를 줄일 수 있음
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      # [CHANGED] 엔티티 기준 DDL 스냅샷 파일 생성 (DB에는 적용 안 함)
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: none
            scripts:
              action: create
              create-target: build/generated/hibernate-ddl.sql
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  main:
    web-application-type: none